### ISSUE TITLE
Don't change current anchor as 2byte language (ex.Korean)

### ISSUE THREAD

**Issue by Dneifiend** [cferdinandi/gumshoe#90]
i guess it only support Latin and digit.

ex. head text string is '가나다라', 
ex case more.

# 가나다라
## 아자차 카타파하

```
gumshoe.min.js:2 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#%EA%B2%8C%EC%9E%84%EC%9D%98-%EC%88%9C%EC%84%9C' is not a valid selector.
    at http://localhost:4000/gitbook/gitbook-plugin-intopic-toc/gumshoe.min.js:2:2974
    at d (http://localhost:4000/gitbook/gitbook-plugin-intopic-toc/gumshoe.min.js:2:581)
    at Object.a.init (http://localhost:4000/gitbook/gitbook-plugin-intopic-toc/gumshoe.min.js:2:2932)
    at <anonymous>:1:9
```

**Comment by cferdinandi** [comment]
Duplicate: https://github.com/cferdinandi/gumshoe/issues/67

**Comment by cferdinandi** [comment]
This should be fixed with v4.x: https://github.com/cferdinandi/gumshoe/releases/tag/v4.0.0
